[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=40.6.0",
    "wheel"
]

[tool.black]
line-length = 120
target_version = ["py37", "py38", "py39", "py310"]

[tool.pytest.ini_options]
markers = [
    "datafiles: load datafiles"
]
testpaths = ["tests"]
norecursedirs = [ ".*", "build", "dist", "*.egg", "data", "__pycache__", ".github", "nf_core", "docs"]

[tool.ruff]
select = [
    # Pyflakes
    "F401", # imported but unused
    "F841", # Local variable is assigned to but never used
    # Pycodestyle
    "E501", # Line too long
    # isort
    "I001"
]
line-length = 120
target-version = "py37"

[tool.ruff.isort]
known-first-party = ["nf_core"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]
