# Config file for Python. Mostly used to configure linting of bin/check_samplesheet.py with Black.
# Should be kept the same as nf-core/tools to avoid fighting with template synchronisation.
[tool.black]
line-length = 120
target_version = ["py37", "py38", "py39", "py310"]

[tool.ruff]
select = [
    # Pyflakes
    "F401", # imported but unused
    "F841", # Local variable is assigned to but never used
    # Pycodestyle
    "E501", # Line too long
    # isort
    "I001"
]
line-length = 120
target-version = "py37"

[tool.ruff.isort]
known-first-party = ["nf_core"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]
